review Create & Read 작성, unit test 구현 예정
wecode-bootcamp-korea/15-2nd-R.I.P.-backend pull request #3
Opened 2021-01-04 14:53 UTC by hjulee12

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한 줄 요약
리뷰 페이지 create, read 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
1. 리뷰 페이지 create (post)
- 컨텐츠 작성 페이지 구현 및 이미지 여러 장을 배열로 저장할 수 있도록 구현

2. 리뷰 페이지 read (get)
- prefetch_related, selected_related 사용하여 리뷰 페이지 불러오기 구현.
- 게시판이 아닌 여러 후기가 한 페이지에 구성되어 offset, limit으로 표현

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-01-05 06:03 UTC, lordmyshepherd requested changes

2021-01-05 06:03 UTC, lordmyshepherd commented on board/urls.py
> +# -*- coding: utf-8 -*-
주석 지워주세요~

2021-01-05 06:03 UTC, lordmyshepherd commented on board/views.py
> +
```suggestion
                review = Review(
                    order_id         = data['order_id'], 
                    contents         = data['contents'],
                    product_id       = data['product_id'],
                    star_rating      = 0
                )

```

2021-01-05 06:03 UTC, lordmyshepherd commented on board/views.py
> +                        )
변수명을 정할 때 좀더 명확하게 만들 수 있을 것 같습니다. 또한 아래에서 keyError를 잡아주고 있으므로 위에서 dictionary에 접근하는 방식과 동일한 방식을 사용하는게 가독성면에서 더 좋을 것 같습니다.
```
image_url = data['url']

image_urls = []
for image_url in image_urls:
    ...
```

2021-01-05 06:03 UTC, lordmyshepherd commented on board/views.py
> +                        )
line 16에서는 save() method로 생성을 했는데, line 33에서는 create()를 사용하신 이유가 있나요?
함수에 인자를 전달할 때 인덴트를 맞춰 가독성을 높여주시면 좋을 것 같아요~
```suggestion
                        ReviewImage.objects.create(
                                review_id = review.id,
                                url       = image_url
                        )
```

2021-01-05 06:03 UTC, lordmyshepherd commented on board/views.py
> +
위 두가지 질문에 대한 답을 찾으셨다면 `for 문` 대신 `list comprehension` 표현식을 적용해보세요

2021-01-05 06:03 UTC, lordmyshepherd commented on board/views.py
> +        except Review.DoesNotExist as e:
해당 에러는 언제 발생할 수 있나요?

2021-01-05 06:03 UTC, lordmyshepherd commented on board/views.py
> +            limit += offset
`try문` 밖으로 빼도 좋을 것 같습니다~

2021-01-07 13:22 UTC, hjulee12 commented on board/views.py
> +                        )
위와 동일하게 save()로 수정하고, indent 맞춰 수정하였습니다.

2021-01-07 13:24 UTC, hjulee12 commented on board/views.py
> +
아직 list comprehension 완전히 익숙하지 않고, 다른 기능구현으로 인해 코드 리팩토링을 못했습니다. review create부분은 원희님이 작성하기로 해서 주말에 list comprehension 숙지 후 리팩토링 해보겠습니다.

2021-01-08 02:58 UTC, lordmyshepherd requested changes

2021-01-08 02:58 UTC, lordmyshepherd commented on board/views.py
> +#
주석은 지워주세요~

2021-01-08 02:58 UTC, lordmyshepherd commented on board/views.py
> +#            return JsonResponse({"MESSAGE":"INVALID_USER"}, status=400)
주석은 지워주세요~

2021-01-08 02:58 UTC, lordmyshepherd commented on board/views.py
> +
사용하지 않는 코드는 지워주세요~

2021-01-08 02:58 UTC, lordmyshepherd commented on board/views.py
> +    #@login_required
원희님 pr이 merge되고 데코레이터도 추가해주세요

2021-01-08 05:33 UTC, lordmyshepherd approved these changes

2021-01-08 05:33 UTC, lordmyshepherd commented
LGTM 👍

2021-01-08 05:35 UTC, lordmyshepherd commented
feed에도 `select_related`와 `prefetch_related`를 적용해보세요~

2021-01-08 05:35 UTC, merged