[Add] feature/user-signup: 회원가입 기능 및 테스트 구현
wecode-bootcamp-korea/15-2nd-R.I.P.-backend pull request #4
Opened 2021-01-05 07:22 UTC by supersaloon

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
email 계정 회원가입 및 테스트 구현

		 
## 수정 사항들 자세한 내용
- 회원가입 기능 및 테스트 구현
  - 회원가입 성공한 경우 201 리턴
  - 형식에 맞지 않는 패스워드를 입력한 경우 400 리턴
  - 형식에 맞지 않는 이메일을 입력한 경우 400 리턴
  - email로 이미 가입된 경우 400 리턴
  - email(카카오 계정)으로 이미 가입된 경우 400 리턴
  - 문자 메세지 인증이 되어 있지 않은 경우 400 리턴

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-01-06 11:58 UTC, lordmyshepherd requested changes

2021-01-06 11:58 UTC, lordmyshepherd commented on user/tests.py
> +        client = Client()
client 객체를 각각의 함수가 실행될 때마다 생성할 필요가 있나요?
setup에서 client 객체를 생성해주면 SignUpTest의 속성에 추가해 놓고 여러 테스트 케이스에서 사용할 수 있습니다~

2021-01-06 11:58 UTC, lordmyshepherd commented on user/tests.py
> +    @classmethod
여기서 `classmethod`를 사용하신 이유가 있나요?

2021-01-06 11:58 UTC, lordmyshepherd commented on user/tests.py
> +    }
setup에 넣어주시면 될 것 같습니다~

2021-01-06 11:58 UTC, lordmyshepherd commented on user/tests.py
> +    def setUpTestData(cls):
`tearDown()`는 만들지 않은 이유가 있으신가요?

2021-01-06 11:58 UTC, lordmyshepherd commented on user/tests.py
> +    }
setup에 선언된 변수들은 setup 함수가 종료되고 사라지는 지역변수가 아니라 `SignUpTest`의 속성으로 저장해 놓을 수 있습니다.

2021-01-06 11:58 UTC, lordmyshepherd commented on user/tests.py
> +            account_type_id = 2,
여기서 account_type_id를 단순히 int로 주게 되면 나중에 테스트 코드가 많아지면 테스트 코드가 정상적으로 동작하지 않을 수 있습니다.
이유가 무었일까요?
**[hint]**
tearDown method를 활용해서 setup에서 만들었던 데이터가 여전히 test_db에 존재할 경우 다음에 다른 테스크 코드가 동작할 때 여전히 데이터베이스에 값이 존재하므로 영향을 줄 수 있습니다.

어떻게 수정해야 좋을까요?

2021-01-06 11:58 UTC, lordmyshepherd commented on user/utils.py
> +
빈칸은 지워주세요.

2021-01-06 11:58 UTC, lordmyshepherd commented on user/views/signup_views.py
> +                    account_type_id = 1,
동료들이 코드를 읽을 때, 이 숫자 1이 무엇을 의미하는지 알 수 있나요?
```suggestion
                    account_type_id = 1,

```

2021-01-07 02:02 UTC, supersaloon commented on user/tests.py
> +    @classmethod
테스트 케이스를 만들 때 아래의 문서를 참조하였습니다.
https://developer.mozilla.org/ko/docs/Learn/Server-side/Django/Testing

![image](https://user-images.githubusercontent.com/69733417/103838727-212e4700-50d1-11eb-9068-f1dbf3a0d9fe.png)
위와 같은 형식의 예시가 있어서 적용하여 보았습니다.

위의 예시에서 `@classmethod`를 사용하지 않고 `setUpTestData(self):` 로 코드를 실행키면 아래와 같은 에러가 발생하였습니다.
```
======================================================================
ERROR: setUpClass (user.tests.SignUpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\castl\anaconda3\envs\rip_dev\lib\site-packages\django\test\testcases.py", line 1123, in setUpClass
    cls.setUpTestData()
TypeError: setUpTestData() missing 1 required positional argument: 'self'

----------------------------------------------------------------------
```

2021-01-07 02:03 UTC, supersaloon commented on user/tests.py
> +        client = Client()
setUp에 client 객체 선언하고 각 메소드에서 받아서 사용하도록 수정하였습니다.

2021-01-07 02:03 UTC, supersaloon commented on user/tests.py
> +    }
setUp에 `new_user` 변수 선언하고 각 메서드에서 받아서 사용하도록 수정하였습니다.

2021-01-07 02:03 UTC, supersaloon commented on user/tests.py
> +    def setUpTestData(cls):
테스트 케이스를 만들 때 참조한 아래의 문서에서
https://developer.mozilla.org/ko/docs/Learn/Server-side/Django/Testing

![image](https://user-images.githubusercontent.com/69733417/103839766-7b300c00-50d3-11eb-8558-5c893c8a8dee.png)

위와 같은 내용이 있었고

직접 테스트 해보니, `tearDown()`을 하지 않아도 각각의 테스트 메서드로 넘어갈 때 데이터가 리셋되는 것을 확인하였습니다.

그래서 전역으로 사용할 데이터는 `def setUpTestData(cls):`에서 담아두고, 변경될 데이터는 각각의 테스트 안에서 추가하는 전략으로 취해보았습니다.

2021-01-07 02:03 UTC, supersaloon commented on user/tests.py
> +            account_type_id = 2,
정적으로 account_type_id = 2라고 하지 않고 아래와 같이 동적으로 DB에거 값을 받아오면서 명확한 변수명을 사용하도록 수정했습니다.
```
email_account_type = AccountType.objects.get(name="email")


account_type = email_account_type,
```

2021-01-07 02:03 UTC, supersaloon commented on user/views/signup_views.py
> +                    account_type_id = 1,
이부분도 위와 같이 

`email_account_type = AccountType.objects.get(name="email")` 와 같은 방식으로 수정하였습니다.

2021-01-07 02:03 UTC, supersaloon commented on user/utils.py
> +
빈칸 삭제하도록 하겠습니다.

2021-01-07 07:18 UTC, lordmyshepherd commented on user/tests.py
> +    def setUpTestData(cls):
정말👍  
맞습니다 원희님! TestCase class는 자동으로 tearDownClass method를 호출하기 때문에 사용하지 않아도 됩니다.
또한 test_method가 실행될때마다 새로운 인스턴스를 생성하기 때문에, setup()에서 생성한 값은 해당 인스턴스에서만 공유할수 있는 반면에 classmethod를 사용하게되면 모든 인스턴스가 setUpTestData(cls)에서 생성된 값을 사용할 수 있게 됩니다.
cls <-- 공통 class
self <-- class에서 생성된 하나의 instance

이를 테스트해보려면 test_method가 실행될때마다 `print(id(self))`를 해보시면 실제로 저장된 메모리 주소가 다름을 알 수 있습니다.

2021-01-07 07:20 UTC, lordmyshepherd approved these changes

2021-01-07 07:20 UTC, lordmyshepherd commented on user/tests.py
> +    @classmethod
이유는 Django source 코드를 확인해보면 setUpTestData를 오버라이딩 해서 사용할 경우 classmethod로 구현하도록 강제되있기 때문입니다~
시간날 때 확인해보세요~

2021-01-07 07:20 UTC, lordmyshepherd commented
LGTM 👍

2021-01-07 07:20 UTC, merged