[Add] feature/user-sms_authentication: 인증용 sms 발송, 발송된 sms로 인증 및 테스트 구현 완료
wecode-bootcamp-korea/15-2nd-R.I.P.-backend pull request #6
Opened 2021-01-05 14:13 UTC by supersaloon

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
인증용 sms 발송, 발송된 sms로 인증 및 테스트 구현 완료

		 
## 수정 사항들 자세한 내용
- 사용자가 요청한 번호로 sms 발송
  - 형식에 맞지 않는 전화번로 요청하면 400 리턴
- 발송된 sms에 대해서 인증요청하면 DB 확인하여 인증처리
  - 형식에 맞니 않는 전화번로 요청하면 400 리턴
  - sms 요청한 전화번호가 아닌 다른 번호로 요청하면 400 리턴

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-01-07 02:03 UTC, lordmyshepherd requested changes

2021-01-07 02:03 UTC, lordmyshepherd commented on tests/test_signin.py
> +class SignInTest(TestCase):
해당 코드는 #4 #5 pr에도 올라왔던 코드 아닌가요?
다른 pr에서 중복된 코드들이 올라오는 것 같습니다! 확인해주세요~

2021-01-07 02:03 UTC, lordmyshepherd commented on tests/test_signup.py
> +class SignUpTest(TestCase):
마찬가지로 중복된 코드가 올라온 것 같습니다.

2021-01-07 02:03 UTC, lordmyshepherd commented on user/views/signup_views.py
> +class SigupUpView(View):
마찬가지입니다.

2021-01-07 02:03 UTC, lordmyshepherd commented on user/views/sms_authentication_views.py
> +        }
`SendSmsView`에는 호출되는 API 관련 코드만 있는게 좋을 것 같습니다.
해당 함수는 외부 모듈로 빼주세요~

2021-01-07 02:03 UTC, lordmyshepherd commented on user/views/sms_authentication_views.py
> +        }
아니면 SMSAPI class를 생성해서 그 안에 여러 메소드들로 만들어줘도 좋을 것 같아요~

2021-01-07 02:03 UTC, lordmyshepherd commented on user/views/sms_authentication_views.py
> +        requests.post(SMS_URL, headers=headers, json=data)
여기 함수에서 return을 해주지 않으면 None이 반환되겠지만, 만약에 post 요청을 보냈는데 성공이 아니라 실패한 경우라면 어떻게 될까요? 

이 경우에도 해당 API는 `{'MESSAGE': 'SUCCESS'}`를 리턴하겠죠?

서드파티 API를 사용할때는 정상처리 되었는지 체크하는 과정이 필요합니다.

2021-01-07 02:47 UTC, supersaloon commented on user/views/signup_views.py
> +class SigupUpView(View):
중복 코드 올라가지 않도록 삭제하겠습니다.

2021-01-07 02:47 UTC, supersaloon commented on user/views/sms_authentication_views.py
> +        }
utils.py 로 이동시키도록 하겠습니다.

2021-01-07 02:47 UTC, supersaloon commented on user/views/sms_authentication_views.py
> +        requests.post(SMS_URL, headers=headers, json=data)
서드파티 API에서 정상적으로 SMS 전송했는지 확인하여
정상인 경우에만 SUCCESS 를 return 하도록 수정하였습니다.

2021-01-07 02:47 UTC, supersaloon commented on tests/test_signup.py
> +class SignUpTest(TestCase):
중복 코드 올라가지 않도록 삭제하겠습니다.

2021-01-07 02:47 UTC, supersaloon commented on tests/test_signin.py
> +class SignInTest(TestCase):
중복 코드 올라가지 않도록 삭제하겠습니다.

2021-01-08 02:30 UTC, lordmyshepherd commented
컨플릭트만 해결해주세요~

2021-01-08 04:07 UTC, lordmyshepherd commented
LGTM 👍

2021-01-08 04:07 UTC, merged